


INSERT INTO vocabs (id, korean, japanese, english, polish)
VALUES
    (149,'교통d','交通d','trafficd','ruch drogowdy');



(1, '미리','あらかじめ', 'in advance', 'wcześniej'),
    (2, '부지런하다','勤勉する', 'Be diligent', 'ciężko pracować'),
    (3, '아끼다','せつやくする', 'economising', 'oszczędzać'),
    (5,'즐기다','楽しむ','enjoy','bawić się, cieszyć się'),
    (6,'차례대로','順番で','In turn, in order','po kolei'),
    (7,'글자','文字','letters','litery'),
    (8,'음감','音感','hearing sense','zmysł słuchu'),
    (9,'뛰어나다','優れている','outstanding','wybitny'),
    (10,'사교젹이다','社交的 ','sociable','towarzyski, społeczny'),
    (11,'손재주가 좋다','手付きがよい','good dexterity','mieć zręczne ręce'),
    (12,'재주','才能','skill','umiejętność'),
    (13,'설득력이 있다','説得力がある','persuasive','przekonujący'),
    (14,'이해가 빠르다','物分りが速い','quick to understand','szybko rozumieć'),
    (15,'책임감이 강하다','責任感が強い','strong sense of responsibility','silne poczucie odpowiedzialności'),
    (16,'소질이있다','手筋がいい','have a knack',' Mieć talent, mieć zdolności'),
    (17,'진로를 정하다','進路をきめる','choose a career path','wybierać ścieżkę kariery'),
    (18,'적성에 맞다','適性に合っている ','fit the aptitude','pasować do zdolności'),
    (19,'목이 따끔거리다','のどが チクチク する','sore throat','ból gardła'),
    (20,'정하다','決める','Choose','Wybierać'),
    (21,'전공을 살리다','専攻を生かす','Make the most of your major','wykorzystać swoją specjalizację'),
    (22,'예술적','芸術的','artistic','artystyczny'),
    (23,'실용적','実用的','useful','użyteczne'),
    (24,'사교적','社交的','sociable','towarzyski'),
    (25,'적극적','[積極的,せっきょくてき]','active','aktywny'),
    (26,'긍정적','肯定的','positive','pozytywny,radosny'),
    (27,'모임','[集まり, 集会]','meeting','spotkanie'),
    (28,'목이마르다','喉が渇わく','thirsty','spragniony'),
    (29,'눈이 침침하다','目がうす暗い','eyes are dim','oczy są przyćmione'),
    (30,'목이 뻣뻣하다','首がごわつく ','stiff neck','sztywny kark'),
    (31,'속이 거복하다','胃袋の調子が悪い','feel upset','czuć się zdenerwowanym'),
    (32,'가슴이 답답하다','胸苦しい','(feeling of) tightness in the chest','(uczucie) ucisku w klatce piersiowej'),
    (33,'막히다','[ふさがる,塞がる]','blocked','zablokowany'),
    (34,'속이 쓰리다','胸焼けする','feel upset','czuć się zdenerwowanym'),
    (35,'봇다','[ふやける, ほとびる]','see','zobaczyć'),
    (36,'가렵다','痒い','itchy','swędzący'),
    (37,'저리다','[ずきずき痛む, しびれる]','numb','zdrętwiały'),
    (38,'모기','蚊','mosquito','komar'),
    (39,'창문','窓','window','okno'),
    (40,'온몸','総身','whole body','Całe ciało'),
    (41,'침을 삼키다','つばを飲込む','swallow saliva','połknąć ślinę'),
    (42,'차금, 빚이','借金','debt','dług'),
    (43,'영향','影響','effect','efekt'),
    (44,'여전히','[相変わらず, 依然として,今も変わらず]','As usual, still,','Jak zwykle, nadal'),
    (45,'기생충','寄生虫','parasite​','pasożyt'),
    (46,'발목','足首','ankle','kostka'),
    (47,'삐다','くじく ','sprain','zwichnąć'),
    (48,'금방','[間もなく, たった今, すぐ]','soon','wkrótce'),
    (49,'지내다','[過ごす, 暮らす, 交わる]','stay, live','zostać, żyć, przebywać'),
    (50,'증상','症状','symptom ','objaw, symptom'),
    (51,'심하다','[はなはだしい, 激げしい, 厳びしい]','Severe','[ciężki,silny,poważny]'),
    (52,'정형외과','整形外科','Orthopedics','oddz. Ortopedyczny'),
    (53,'붓다','腫れる','swell','puchnąć'),
    (54,'생강','生姜','ginger','imbir'),
    (55,'여러','[さまざま, いろいろ]','several','kilka'),
    (56,'아쉽게도','残念ながら','Unfortunately','Niestety'),
    (57,'지각','遅刻','lateness, tardiness','spóźnienie'),
    (58,'머리가 어지럽다','めまぐるしい','feel dizzy','mieć zawroty głowy'),
    (59,'도둑','泥棒','a thief ','złodziej '),
    (60,'놓치다','[落とす, 失う, 逃がす]','to let go','odpuścić sobie, oswobodzić'),
    (61,'넘어지다','[倒れる, 転ぶ, 敗れる]','fall down','upaść'),
    (62,'두딪치다','ぶつかり合あう','bump into','wpadać na coś'),
    (63,'상대편','相手側','the other side, the other party','druga strona, partner'),
    (64,'문을 닫다','店を閉しめる, 門を打つ  ','close the door, close business','zamknąć drzwi, zmknąć firmę'),
    (65,'바닥','床','floor','podłoga'),
    (66,'발바닥','足の裏','sole of foot​','dolna część stopy'),
    (67,'추천하다','勧める','recommend','polecać'),
    (68,'땅자닥','地面','ground','grunt'),
    (69,'쏟다','注ぐ','pour out, pour','wylać, nalać'),
    (70,'숭진하다','[純真, 素直]','to be noble','być szlachetnym'),
    (71,'다내다',' 振う','run out','skończyć się'),
    (72,'더럽다','汚い','dirty','brudny'),
    (73,'얼다','凍る','freeze','zamrażać'),
    (74,'끓이다','沸騰する','boil','gotować'),
    (75,'밤마다','毎晩','every night','każda noc'),
    (76,'금방','[今すぐ, 間もなく]','soon','wkrótce'),
    (77,'장소','場所','Place','Miejsce'),
    (78,'자기','自分','self','samego siebie'),
    (79,'필통','筆箱','pencilcase','piórnik'),
    (80,'직장','職場','rectal','odbytniczy'),
    (81,'선택','選択','select','wybierać'),
    (82,'이유','理由','Reason','Powód'),
    (83,'근무','勤務','work','Praca'),
    (84,'환경','環境','environment','środowisko'),
    (85,'중요하다','[重要,大切]','It is important','To jest ważne'),
    (86,'이유','理由','Reason','Powód'),
    (87,'졸업','卒業','Graduated','Absolwent'),
    (88,'취직','就職','find a job','Znajdź pracę'),
    (89,'드디어','ついに','finally','wreszcie'),
    (90,'작품','作品','Work','Praca'),
    (91,'모임','[集まり , 集会]','class','klasa'),
    (92,'성격','性格','personality','osobowość'),
    (93,'눈이 침침하다','目がうす暗い','my eyes are dim','moje oczy są przyćmione'),
    (94,'목이 따끔거리다','のどがひりひりする','sore throat','ból gardła'),
    (95,'목이 뻣뻣하다','首がごわつく','stiff neck','sztywna szyja, sztywny kark'),
    (96,'목이 마르다','のどが渇く','thirsty','spragniony'),
    (97,'속이 거복하다','胃袋の調子が悪い','feel upset, ','czuć się zdenerwowanym, mieć wzdęty brzuch'),
    (98,'가슴이 답답하다','胸苦しい ','have a heavy heart ','ciężko na sercu'),
    (99,'막히다','塞(ふさ)がる','blocked','zablokowany'),
    (100,'봇다','腫れる','swell','spuchnąć'),
    (101,'가렵다','痒い','itchy','swędzenie'),
    (102,'저리다','[ずきずき痛む, しびれる]','numb','zdrętwiały'),
    (103,'모기','[カ,(蚊)]','mosquito','komar'),
    (104,'창문','窓','window','okno'),
    (105,'온몸','総身','whole body','Całe ciało'),
    (106,'침을 삼키다','つばを飲込む','swallow saliva','połknąć ślinę'),
    (107,'기름지다','油っこい','oily','oleisty'),
    (108,'나이가 들다','[年が寄る,老ける]','getting old','starzeć się'),
    (109,'코를 풀다','鼻をかむ','blow nose','wydmuchać nos'),
    (110,'무릎을 꿇다','[ひざまずく, 膝をつく]','kneel','klęczeć'),
    (111,'친하다','[親しい,近しい]','close','bliski'),
    (112,'믿다','[信ずる,信じる]','believe','wierzyć'),
    (113,'오해하다','思い違える','Misconceive, misunderstand','Źle zrozumieć'),
    (114,'속상하다','[癪にさわる, 気にさわる,]','upset','smutny'),
    (115,'소화','消化','digestion','trawienie'),
    (116,'다리','足','leg','noga'),
    (117,'다치다','[傷つく,けがする, 痛める]','get hurt','Zranić się'),
    (118,'제대로',' [ちゃんと,きちんと]','properly','odpowiednio, porządnie'),
    (119,'걷다','歩く','To Walk','Chodzić'),
    (120,'과로','過労','strain','napięcie'),
    (121,'과식','[過食,食べ過ぎ]','surfeit','przejedzenie'),
    (122,'과음','[過飲,飲過ぎ]','Overdrinking','Nadmierne picie'),
    (123,'과속','[過速,超過速度]','Speeding','Nadmierna prędkość'),
    (124,'과소비','[過度な消費,過消費]','overspending','nadmierne wydatki'),
    (125,'이익','利益','profit','zysk'),
    (126,'편히','ゆっくり','at ease, slowly','z łatwością, powoli'),
    (127,'논문','論文','thesis,  paper, article​','Praca dyplomowa, praca naukowa'),
    (128,'속상하다','[気にさわる,気を病む]','upset','smutny'),
    (129,'헤어지다','[別れる,離れる]','break up, to part ','zerwać, rozstać się, oddalić się'),
    (130,'미술','美術','Art','Sztuka'),
    (131,'오래','[長く,久しく]','long','długo'),
    (132,'남녀노소','男女老少','everyone','wszyscy(bez względu na wiek i płeć)'),
    (133,'두부','豆腐','tofu','tofu'),
    (134,'지키다','守る','Protect','Ochraniać'),
    (135,'소중','大切','precious','cenny'),
    (136,'젊다','若い','young','młody'),
    (137,'젊은이','若者','young people','młodzi ludzie'),
    (138,'불편','不便','Inconvenience','Niedogodność'),
    (139,'감동적이다','感動的','to be touched ','być dotkniętym '),
    (140,'집중하다','集中する','Concentrate on','koncentrować się '),
    (141,'상대','相手','opponent','przeciwnik'),
    (142,'우승','優勝','Championship','Mistrzostwo'),
    (143,'지다','負ける','lose','stracić'),
    (144,'실례','失礼','discourtesy, impoliteness','ujma na honorze, niegrzeczność'),
    (145,'단풍이','紅葉','autumn leaves','jesienne liście'),
    (146,'합격','合格','pass','podawać'),
    (147,'편리하다','便利','convenient','wygodny'),
    (148,'교통','交通','traffic','ruch drogowy');




